
Metrics/ParameterLists:
  Max: 8

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Style/RescueStandardError:
  EnforcedStyle: implicit

Metrics/BlockLength:
  Exclude:
  - '**/*.rake'

# TODO: remove
Metrics/LineLength:
  Max: 270

Lint/ConstantDefinitionInBlock:
  Enabled: false