
Metrics/ParameterLists:
  Max: 8

Metrics/MethodLength:
  Max: 20

Style/SpecialGlobalVars:
  Exclude:
    - 'main.rake'

Metrics/BlockLength:
  Exclude:
  - '**/*.rake'

# TODO: remove
Metrics/LineLength:
  Max: 270

# TODO: remove
Lint/RescueException:
  Exclude:
    - 'setup.rake'
