
Metrics/ParameterLists:
  Max: 8

Metrics/MethodLength:
  Max: 20

Style/SpecialGlobalVars:
  Exclude:
    - 'main.rake'

# TODO: remove
Metrics/LineLength:
  Max: 270

# TODO: remove
Lint/RescueException:
  Exclude:
    - 'setup-project.rake'
