app_name: MyWeight
workspace_path: MyWeight.xcworkspace
project_path: MyWeight.xcodeproj

bundler:
  path: # or taken from ENV['BUNDLER_PATH']

swiftgen:
  path: Pods/SwiftGen/bin/swiftgen
  strings:
    'Watch Extension/Resources/en.lproj/Localizable.strings': 'Watch Extension/Generated/L10n.swift'

test_archive:
  build_path: build # or taken from ENV['ARTIFACTS_PATH']
  reports_path: reports # or taken from ENV['TEST_REPORTS_PATH']
  unit_tests:
    scheme: MyWeight
    destinations:
      - 'platform=iOS Simulator,OS=10.3,name=iPhone SE'
  release:
    prod:
      scheme: MyWeight
      configuration: Release
      output: MyWeight
    dev:
      scheme: 'MyWeight Dev'
      configuration: Release
      output: 'MyWeight Dev'
